import { User, Simulation, SkillData, Recommendation, Job, Achievement } from './types';

export const mockUser: User = {
  name: "An Nguyen",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=An",
  email: "an.nguyen@student.edu.vn",
  joinDate: "2024-09-15",
  simulationsStarted: 12,
  simulationsCompleted: 8,
  averageScore: 84.5,
  currentStreak: 12,
  longestStreak: 18,
  learningDaysThisWeek: 5,
  totalHoursLearned: 34.5,
  rank: "Rising Star",
  rankPosition: 234,
  totalUsers: 15420,
  certificates: 8,
  level: 7,
  xp: 3450,
  nextLevelXp: 4000
};

export const mockSimulations: Simulation[] = [
  {
    id: 1,
    title: "AI Product Manager - Market Analysis & Strategy",
    company: "Google",
    logo: "🔍",
    role: "AI Product Manager",
    difficulty: "Advanced",
    status: "completed",
    progress: 100,
    score: 92,
    lastActivity: "2024-12-05",
    completedDate: "2024-12-05",
    startedDate: "2024-12-03",
    skills: ["Data Analysis", "Strategic Thinking", "Domain Knowledge"],
    estimatedTime: "3 hours",
    actualTime: 2.8,
    steps: 5,
    completedSteps: 5,
    xpEarned: 450,
    popularity: 95,
    completionRate: 68
  },
  {
    id: 2,
    title: "Data Analyst - Customer Segmentation & Insights",
    company: "Lazada",
    logo: "🛒",
    role: "Data Analyst",
    difficulty: "Intermediate",
    status: "in-progress",
    progress: 75,
    score: null,
    lastActivity: "2024-12-07",
    startedDate: "2024-12-06",
    skills: ["Data Analysis", "Problem Solving", "Technical Skills"],
    estimatedTime: "2.5 hours",
    actualTime: 1.9,
    steps: 4,
    completedSteps: 3,
    xpEarned: 0,
    popularity: 88,
    completionRate: 72
  },
  {
    id: 3,
    title: "Digital Marketing - Multi-Channel Campaign Strategy",
    company: "Grab",
    logo: "🚗",
    role: "Marketing Executive",
    difficulty: "Beginner",
    status: "completed",
    progress: 100,
    score: 78,
    lastActivity: "2024-12-03",
    completedDate: "2024-12-03",
    startedDate: "2024-12-02",
    skills: ["Interpersonal skill", "Strategic Thinking", "Stakeholder Management"],
    estimatedTime: "2 hours",
    actualTime: 2.2,
    steps: 3,
    completedSteps: 3,
    xpEarned: 320,
    popularity: 92,
    completionRate: 85
  },
  {
    id: 4,
    title: "Backend Engineer - RESTful API Design & Implementation",
    company: "Masterise",
    logo: "💻",
    role: "Backend Developer",
    difficulty: "Advanced",
    status: "in-progress",
    progress: 60,
    score: null,
    lastActivity: "2024-12-07",
    startedDate: "2024-12-05",
    skills: ["Technical Skills", "Problem Solving", "Domain Knowledge"],
    estimatedTime: "4 hours",
    actualTime: 2.4,
    steps: 5,
    completedSteps: 3,
    xpEarned: 0,
    popularity: 87,
    completionRate: 64
  },
  {
    id: 5,
    title: "PR Specialist - Crisis Interpersonal skill & Brand Management",
    company: "Heineken",
    logo: "🍺",
    role: "PR & Interpersonal skills",
    difficulty: "Intermediate",
    status: "completed",
    progress: 100,
    score: 95,
    lastActivity: "2024-12-01",
    completedDate: "2024-12-01",
    startedDate: "2024-11-30",
    skills: ["Interpersonal skill", "Stakeholder Management", "Strategic Thinking"],
    estimatedTime: "2 hours",
    actualTime: 1.8,
    steps: 4,
    completedSteps: 4,
    xpEarned: 380,
    popularity: 90,
    completionRate: 78
  },
  {
    id: 6,
    title: "UX Designer - User Research & Prototyping",
    company: "Twitter",
    logo: "🐦",
    role: "UX Designer",
    difficulty: "Intermediate",
    status: "not-started",
    progress: 0,
    score: null,
    lastActivity: null,
    skills: ["Problem Solving", "Interpersonal skill", "Design Thinking"],
    estimatedTime: "3 hours",
    actualTime: 0,
    steps: 4,
    completedSteps: 0,
    xpEarned: 0,
    popularity: 94,
    completionRate: 81
  },
  {
    id: 7,
    title: "Product Manager - Feature Prioritization Workshop",
    company: "Shopee",
    logo: "🛍️",
    role: "Product Manager",
    difficulty: "Advanced",
    status: "completed",
    progress: 100,
    score: 88,
    lastActivity: "2024-11-28",
    completedDate: "2024-11-28",
    startedDate: "2024-11-26",
    skills: ["Strategic Thinking", "Stakeholder Management", "Problem Solving"],
    estimatedTime: "3.5 hours",
    actualTime: 3.2,
    xpEarned: 420,
    steps: 5,
    completedSteps: 5,
    popularity: 91,
    completionRate: 70
  },
  {
    id: 8,
    title: "Financial Analyst - Investment Portfolio Analysis",
    company: "Morgan Stanley",
    logo: "💼",
    role: "Financial Analyst",
    difficulty: "Advanced",
    status: "completed",
    progress: 100,
    score: 82,
    lastActivity: "2024-11-25",
    completedDate: "2024-11-25",
    startedDate: "2024-11-23",
    skills: ["Data Analysis", "Strategic Thinking", "Domain Knowledge"],
    estimatedTime: "3 hours",
    actualTime: 3.1,
    xpEarned: 440,
    steps: 5,
    completedSteps: 5,
    popularity: 86,
    completionRate: 65
  }
];

export const mockSkills: Record<string, SkillData> = {
  "Data Analysis": { current: 82, previous: 75, trend: "up" },
  "Interpersonal Skill": { current: 88, previous: 85, trend: "up" },
  "Problem Solving": { current: 76, previous: 78, trend: "down" },
  "Stakeholder Management": { current: 85, previous: 80, trend: "up" },
  "Technical Skills": { current: 71, previous: 65, trend: "up" },
  "Strategic Thinking": { current: 84, previous: 82, trend: "up" },
  "Domain Knowledge": { current: 79, previous: 75, trend: "up" },
  "Design Thinking": { current: 52, previous: 45, trend: "up" }
};

export const mockRecommendations: Recommendation[] = [
  {
    id: 101,
    title: "Advanced Data Visualization with Python & Tableau",
    company: "Google",
    logo: "🔍",
    difficulty: "Advanced",
    estimatedTime: "3.5 hours",
    reason: "Perfect next step to master Data Analysis - builds on your 82% proficiency",
    skills: ["Data Analysis", "Technical Skills"],
    match: 94,
    trending: true,
    enrollments: 1250
  },
  {
    id: 102,
    title: "Design Thinking Masterclass - From Problem to Solution",
    company: "IDEO",
    logo: "🎨",
    difficulty: "Intermediate",
    estimatedTime: "2.5 hours",
    reason: "Boost your weakest skill - Design Thinking from 52% to expert level",
    skills: ["Design Thinking", "Problem Solving", "Interpersonal skill"],
    match: 91,
    trending: true,
    enrollments: 890
  },
  {
    id: 103,
    title: "Agile Problem Solving & Critical Thinking",
    company: "Lazada",
    logo: "🛒",
    difficulty: "Intermediate",
    estimatedTime: "2 hours",
    reason: "Strengthen Problem Solving and reverse recent decline",
    skills: ["Problem Solving", "Strategic Thinking"],
    match: 88,
    trending: false,
    enrollments: 2100
  },
  {
    id: 104,
    title: "Full-Stack Web Development - MERN Stack",
    company: "Meta",
    logo: "👨‍💻",
    difficulty: "Advanced",
    estimatedTime: "5 hours",
    reason: "Expand your Technical Skills with modern frameworks",
    skills: ["Technical Skills", "Problem Solving"],
    match: 85,
    trending: true,
    enrollments: 3400
  }
];

export const mockJobs: Job[] = [
  {
    id: 201,
    title: "Junior Data Analyst",
    company: "Shopee",
    location: "Ho Chi Minh City",
    type: "Full-time",
    salary: "$800-1200/month",
    skills: ["Data Analysis", "Technical Skills", "Problem Solving"],
    match: 92,
    posted: "2 days ago",
    applicants: 45
  },
  {
    id: 202,
    title: "Marketing Coordinator",
    company: "Grab",
    location: "Remote",
    type: "Full-time",
    salary: "$900-1400/month",
    skills: ["Interpersonal skill", "Strategic Thinking"],
    match: 88,
    posted: "1 week ago",
    applicants: 67
  },
  {
    id: 203,
    title: "Product Management Intern",
    company: "Lazada",
    location: "Hybrid - Hanoi",
    type: "Internship",
    salary: "$400-600/month",
    skills: ["Strategic Thinking", "Stakeholder Management", "Problem Solving"],
    match: 85,
    posted: "3 days ago",
    applicants: 34
  }
];

export const achievements: Achievement[] = [
  { id: 1, title: "Fast Learner", description: "Complete 5 simulations", icon: "⚡", earned: true, date: "2024-11-20" },
  { id: 2, title: "Perfectionist", description: "Score 90+ on 3 simulations", icon: "💎", earned: true, date: "2024-12-01" },
  { id: 3, title: "Streak Master", description: "Maintain 10-day streak", icon: "🔥", earned: true, date: "2024-12-04" },
  { id: 4, title: "Diverse Skills", description: "Complete simulations in 5 different roles", icon: "🌈", earned: true, date: "2024-11-25" },
  { id: 5, title: "Elite Performer", description: "Reach top 500 globally", icon: "👑", earned: true, date: "2024-12-05" },
  { id: 6, title: "Career Explorer", description: "Complete 10 simulations", icon: "🗺️", earned: false, progress: 80 }
];

